version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27070:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ahojahoj
      MONGO_INITDB_ROOT_PASSWORD: ahojahoj